### ISSUE TITLE
Toolbar color is not applied unless Firefox Color is installed

### ISSUE THREAD

**Issue by ghost** [Zabooby/firefox-config#1]
## Description
Seems like a bit of a weird error as the toolbar color `--toolbar-bgcolor` doesn't seem to be applied unless you have the Firefox Color extension installed. I'm not sure what steps are needed to fix this as I'm not knowledgeable in Firefox CSS ricing.

## Tested on
- Windows 11 23H2
- Arch Linux 6.6.10.arch1-1

## Steps to Reproduce
1. Installing everything without having the Firefox Color extension:
![image](https://github.com/Zabooby/firefox-config/assets/134171156/aa7a7c62-dca9-4923-a32b-d7a9a500a885)
2. Installing the Firefox Color extension, and selecting a theme:
![image](https://github.com/Zabooby/firefox-config/assets/134171156/1b5b357a-15ee-4a8a-aa6c-9f04e374088a)

## Notes
The background area of the window actions are overridden by Firefox color (selecting a textured background will show). This toolbar color issue was also present in another updated version of [FlyingFox](https://github.com/Astromations/FlyingFox) by Astromations. 

** Just as a quick edit:
There may be other things that aren't applied unless the Firefox color extension is installed such as Google search suggestion:
![image](https://github.com/Zabooby/firefox-config/assets/134171156/dcffa4e2-bdbd-4c92-b650-723724e42a4c)

**Comment by Zabooby** [comment]
Did a bit of testing, the toolbar colours all work when I install on a fresh profile. If you enable the system dark theme the toolbar issue should be fixed so at least you don't need to install Firefox Color extension.  

Are you experiencing the issue on both Windows and Arch?

I have noticed the search suggestion doesn't apply the correct colours too, I'll look into it (and some other bugs I've noticed once my exams are over. 

Also i just remembered from your screenshots that my config has custom fonts that I haven't added to the repo yet, thanks for the reminder.

**Comment by ghost** [comment]
I'm experiencing the issue on both Windows and Arch, although setting the system dark theme did fix the toolbar so thanks for the fix there. I don't have the font issue on Arch, but I'd have to check what the default font is there (it's definitely not a serif font, I did install noto-fonts while installing Firefox)-- it defaults to Times New Roman on windows.

**Comment by Zabooby** [comment]
Could you install the the fonts I just added and see if displays properly? 

Can I close this issue as you no longer need the extension to fix the toolbar?

**Comment by ghost** [comment]
Yup, the fonts work!
